export interface QuestlogToolMapping {
	source: string;
	tool: string;
	action?: string;
	notes?: string;
}

export const questlogToolMappings: QuestlogToolMapping[] = [
	{ source: 'searchQuestlog', tool: 'search_questlog' },
	{ source: 'listRumors', tool: 'review_questlog', action: 'rumors' },
	{ source: 'listQuestlines', tool: 'review_questlog', action: 'questlines' },
	{ source: 'listOpenQuests', tool: 'review_questlog', action: 'quests.open' },
	{ source: 'listActiveQuests', tool: 'review_questlog', action: 'quests.active' },
	{ source: 'listInProgressQuests', tool: 'review_questlog', action: 'quests.in_progress' },
	{ source: 'listAvailableQuests', tool: 'review_questlog', action: 'quests.available' },
	{ source: 'listBlockedQuests', tool: 'review_questlog', action: 'quests.blocked' },
	{ source: 'listDeferredQuests', tool: 'review_questlog', action: 'quests.deferred' },
	{ source: 'listDueSoonQuests', tool: 'review_questlog', action: 'quests.due_soon' },
	{ source: 'listOverdueQuests', tool: 'review_questlog', action: 'quests.overdue' },
	{ source: 'listScheduledNow', tool: 'review_questlog', action: 'quests.scheduled_now' },
	{ source: 'listScheduledForDay', tool: 'review_questlog', action: 'quests.scheduled_for_day' },
	{
		source: 'listMissedScheduledQuests',
		tool: 'review_questlog',
		action: 'quests.missed_scheduled',
	},
	{ source: 'listResolvedQuests', tool: 'review_questlog', action: 'quests.resolved' },
	{
		source: 'listDueRepeatableQuestAnchors',
		tool: 'review_questlog',
		action: 'repeatables.due_anchors',
	},
	{ source: 'getRumorDetail', tool: 'inspect_questlog_item', action: 'rumor' },
	{ source: 'getQuestDetail', tool: 'inspect_questlog_item', action: 'quest' },
	{ source: 'getQuestlineDetail', tool: 'inspect_questlog_item', action: 'questline' },
	{
		source: 'getRepeatableQuestOrThrow',
		tool: 'inspect_questlog_item',
		action: 'repeatable_quest',
		notes: 'Internal read used so repeatables can also be inspected by the facade.',
	},
	{
		source: 'getRumorOutputs',
		tool: 'inspect_questlog_item',
		action: 'rumor',
		notes: 'Folded into rumor detail data instead of exposed separately.',
	},
	{ source: 'captureRumor', tool: 'capture_rumor' },
	{ source: 'settleRumor', tool: 'shape_work', action: 'settle_rumor' },
	{ source: 'dismissRumor', tool: 'shape_work', action: 'dismiss_rumor' },
	{ source: 'reopenRumor', tool: 'shape_work', action: 'reopen_rumor' },
	{ source: 'createQuest', tool: 'shape_work', action: 'create_quest' },
	{ source: 'createQuestline', tool: 'shape_work', action: 'create_questline' },
	{ source: 'moveQuestToQuestline', tool: 'shape_work', action: 'attach_quest_to_questline' },
	{
		source: 'detachQuestFromQuestline',
		tool: 'shape_work',
		action: 'detach_quest_from_questline',
	},
	{ source: 'reviseQuestObjective', tool: 'plan_quest', action: 'revise_objective' },
	{ source: 'planQuestTime', tool: 'plan_quest', action: 'set_time' },
	{ source: 'startQuest', tool: 'run_quest', action: 'start' },
	{ source: 'logQuestEffort', tool: 'run_quest', action: 'log_effort' },
	{ source: 'finishQuest', tool: 'run_quest', action: 'finish' },
	{ source: 'abandonQuest', tool: 'run_quest', action: 'abandon' },
	{
		source: 'abandonQuestAndSpawnFollowups',
		tool: 'run_quest',
		action: 'abandon_and_spawn_followups',
	},
	{ source: 'updateQuestline', tool: 'organize_work', action: 'set_questline_fields' },
	{ source: 'archiveQuestline', tool: 'organize_work', action: 'archive_questline' },
	{ source: 'addUnlock', tool: 'organize_work', action: 'add_unlock' },
	{ source: 'removeUnlock', tool: 'organize_work', action: 'remove_unlock' },
	{ source: 'replaceUnlocks', tool: 'organize_work', action: 'replace_unlocks' },
	{ source: 'createRepeatableQuest', tool: 'manage_repeatable', action: 'create' },
	{ source: 'updateRepeatableQuest', tool: 'manage_repeatable', action: 'update' },
	{ source: 'archiveRepeatableQuest', tool: 'manage_repeatable', action: 'archive' },
	{ source: 'spawnDueRepeatableQuests', tool: 'manage_repeatable', action: 'spawn_due' },
	{ source: 'tagQuest', tool: 'tag_work', action: 'add' },
	{ source: 'untagQuest', tool: 'tag_work', action: 'remove' },
	{ source: 'replaceQuestTags', tool: 'tag_work', action: 'replace' },
	{ source: 'replaceRepeatableQuestTags', tool: 'tag_work', action: 'replace_repeatable' },
	{ source: 'addQuestReward', tool: 'reward_work', action: 'add' },
	{ source: 'updateQuestReward', tool: 'reward_work', action: 'update' },
	{ source: 'removeQuestReward', tool: 'reward_work', action: 'remove' },
	{ source: 'claimQuestReward', tool: 'reward_work', action: 'claim' },
	{
		source: 'replaceRepeatableQuestRewards',
		tool: 'reward_work',
		action: 'replace_repeatable_template',
	},
	{ source: 'softDeleteRumor', tool: 'retire_work', action: 'hide_rumor' },
	{ source: 'softDeleteQuest', tool: 'retire_work', action: 'hide_quest' },
	{ source: 'softDeleteQuestline', tool: 'retire_work', action: 'hide_questline' },
	{
		source: 'softDeleteRepeatableQuest',
		tool: 'retire_work',
		action: 'hide_repeatable',
		notes: 'Canonical hide path for repeatable quests after the boundary review.',
	},
];
